version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=seenuser
      - MYSQL_PASSWORD=seenpass
      - MYSQL_DATABASE=seendb
      - LANG=es_ES.UTF-8
      - LC_ALL=es_ES.UTF-8

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=seendb
      - MYSQL_USER=seenuser
      - MYSQL_PASSWORD=seenpass
      - LANG=es_ES.UTF-8
      - LC_ALL=es_ES.UTF-8
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --init-connect='SET NAMES utf8mb4'
      --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "seenuser", "-pseenpass"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  mysql_data: 